import type { Scene } from "@/components/cockpit/engine";

/**
 * The instrument register. Each scene is its own chunk, fetched only by the
 * pages that show it; nothing here is in the shared bundle but this map.
 */
type Loader = () => Promise<{ default: Scene<never> | Scene<unknown> | Scene }>;

export const SCENES = {
  accord: () => import("./accord"),
  accounts: () => import("./accounts"),
  annunciator: () => import("./annunciator"),
  atelier: () => import("./atelier"),
  atlas: () => import("./atlas"),
  banks: () => import("./banks"),
  barometer: () => import("./barometer"),
  bastion: () => import("./bastion"),
  beacon: () => import("./beacon"),
  charter: () => import("./charter"),
  clock: () => import("./clock"),
  compound: () => import("./compound"),
  compare: () => import("./compare"),
  compass: () => import("./compass"),
  conditions: () => import("./conditions"),
  constellation: () => import("./constellation"),
  convert: () => import("./convert"),
  copy: () => import("./copy"),
  costs: () => import("./costs"),
  course: () => import("./course"),
  crypto: () => import("./crypto"),
  document: () => import("./document"),
  drawdown: () => import("./drawdown"),
  drawers: () => import("./drawers"),
  energy: () => import("./energy"),
  equities: () => import("./equities"),
  events: () => import("./events"),
  flightdeck: () => import("./flightdeck"),
  forex: () => import("./forex"),
  funding: () => import("./funding"),
  galaxy: () => import("./galaxy"),
  gateway: () => import("./gateway"),
  golden: () => import("./golden"),
  helm: () => import("./helm"),
  horizon: () => import("./horizon"),
  indices: () => import("./indices"),
  instrument: () => import("./instrument"),
  lantern: () => import("./lantern"),
  lattice: () => import("./lattice"),
  leverage: () => import("./leverage"),
  lexicon: () => import("./lexicon"),
  library: () => import("./library"),
  margin: () => import("./margin"),
  markets: () => import("./markets"),
  metals: () => import("./metals"),
  mt5: () => import("./mt5"),
  network: () => import("./network"),
  order: () => import("./order"),
  outcome: () => import("./outcome"),
  pamm: () => import("./pamm"),
  pip: () => import("./pip"),
  platforms: () => import("./platforms"),
  daily: () => import("./daily"),
  press: () => import("./press"),
  prism: () => import("./prism"),
  proof: () => import("./proof"),
  provenance: () => import("./provenance"),
  raptor: () => import("./raptor"),
  ratio: () => import("./ratio"),
  ribbon: () => import("./ribbon"),
  rosette: () => import("./rosette"),
  seal: () => import("./seal"),
  sieve: () => import("./sieve"),
  signal: () => import("./signal"),
  sizing: () => import("./sizing"),
  spread: () => import("./spread"),
  strength: () => import("./strength"),
  strongroom: () => import("./strongroom"),
  switchboard: () => import("./switchboard"),
  threads: () => import("./threads"),
  threshold: () => import("./threshold"),
  trading: () => import("./trading"),
  vault: () => import("./vault"),
  veil: () => import("./veil"),
  workbench: () => import("./workbench"),
} satisfies Record<string, Loader>;

export type SceneId = keyof typeof SCENES;
