-- =============================================================================
-- GIO4X · 0001_init · tables, constraints, indexes
-- -----------------------------------------------------------------------------
-- Apply in order: 0001_init → 0002_security → 0003_triggers.
--
-- The application talks to this database with the PUBLISHABLE key only (no
-- service-role key exists in the application). Row-level security is therefore
-- the security boundary, and the CHECK constraints below are the last line of
-- input validation: a direct PostgREST call with the publishable key must not
-- be able to store anything the API in src/app/api would have rejected.
--
-- Safe at every step: each table is created with row-level security ENABLED and
-- FORCED and with every privilege revoked from the API roles in this same file,
-- so there is no window in which a table is reachable before 0002 adds the
-- precise grants and policies. (Supabase grants ALL on new public tables to
-- anon/authenticated by default; that default is undone here, table by table.)
--
-- Idempotent where practical: IF NOT EXISTS on tables and indexes. Constraints
-- are declared inline, so re-running against an existing table does not alter it.
--
-- Control characters: every single-line text column rejects U+0001–U+001F and
-- U+007F. `message` and note bodies allow tab and newline only.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- staff: who may use GIO4X Control, and in which role.
-- Rows are created by the owner in SQL (see docs/CONTROL.md). There is no API
-- path that can insert, update or delete a staff row.
-- ---------------------------------------------------------------------------
create table if not exists public.staff (
  user_id      uuid primary key references auth.users (id) on delete cascade,
  role         text not null,
  display_name text not null,
  created_at   timestamptz not null default now(),
  constraint staff_role_valid check (role in ('admin', 'agent', 'viewer')),
  constraint staff_display_name_valid check (
    char_length(display_name) between 1 and 80
    and display_name !~ '[\u0001-\u001F\u007F]'
  )
);
comment on table public.staff is 'GIO4X Control staff and roles. Managed in SQL by the owner; never writable through the API.';

alter table public.staff enable row level security;
alter table public.staff force row level security;
revoke all on table public.staff from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- leads: one row per enquiry from a public form.
-- `id` and `reference` are generated by the API (anon cannot SELECT, so the
-- insert cannot use RETURNING to learn a database-generated value).
-- ---------------------------------------------------------------------------
create table if not exists public.leads (
  id                   uuid primary key default gen_random_uuid(),
  reference            text not null,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  name                 text not null,
  email                text not null,
  phone                text,
  country              text,
  topic                text not null,
  message              text not null,
  account_interest     text,
  page                 text not null default '/',
  utm                  jsonb not null default '{}'::jsonb,
  -- consent evidence: what was accepted, when, and which version of the policy
  privacy_accepted_at  timestamptz not null,
  privacy_version      text not null,
  marketing_consent    boolean not null default false,
  marketing_consent_at timestamptz,
  -- staff-controlled
  status               text not null default 'new',
  assigned_to          uuid references public.staff (user_id) on delete set null,

  constraint leads_reference_key unique (reference),
  -- GX- + 8 characters of RFC 4648 base32 (40 random bits)
  constraint leads_reference_format check (reference ~ '^GX-[A-Z2-7]{8}$'),
  constraint leads_name_valid check (
    char_length(name) between 1 and 120 and name !~ '[\u0001-\u001F\u007F]'
  ),
  -- ASCII addresses only, stored lower-case, so equality is case-insensitive
  constraint leads_email_valid check (
    char_length(email) between 6 and 254
    and email = lower(email)
    and email ~ '^[a-z0-9.!#$%&''*+/=?^_`{|}~-]+@[a-z0-9-]+(\.[a-z0-9-]+)+$'
  ),
  constraint leads_phone_valid check (
    phone is null or phone ~ '^[0-9+() ./-]{5,40}$'
  ),
  constraint leads_country_valid check (
    country is null
    or (char_length(country) between 1 and 80 and country !~ '[\u0001-\u001F\u007F]')
  ),
  constraint leads_topic_valid check (topic in (
    'General', 'Account', 'Account opening', 'Platform: 777 Raptor',
    'Platform: MetaTrader 5', 'Technical', 'Partnership', 'Press',
    'Security', 'Privacy', 'Complaint'
  )),
  constraint leads_message_valid check (
    char_length(message) between 1 and 5000
    and char_length(btrim(message)) >= 1
    and message !~ '[\u0001-\u0008\u000B-\u001F\u007F]'
  ),
  constraint leads_account_interest_valid check (
    account_interest is null
    or (char_length(account_interest) between 1 and 80 and account_interest !~ '[\u0001-\u001F\u007F]')
  ),
  -- a same-site path: starts with one slash, never //host, no whitespace, no backslash
  constraint leads_page_valid check (
    char_length(page) between 1 and 300
    and page ~ '^/([^/\\[:space:]][^\\[:space:]]*)?$'
  ),
  -- only the five utm_* keys, string values, bounded size
  constraint leads_utm_valid check (
    jsonb_typeof(utm) = 'object'
    and (utm - array['utm_source', 'utm_medium', 'utm_campaign', 'utm_term', 'utm_content']) = '{}'::jsonb
    and not jsonb_path_exists(utm, '$.* ? (@.type() != "string")')
    and octet_length(utm::text) <= 1024
  ),
  constraint leads_privacy_version_valid check (privacy_version ~ '^[A-Za-z0-9._-]{1,40}$'),
  -- marketing consent is separate from the enquiry and always carries its own timestamp
  constraint leads_marketing_consent_evidence check (marketing_consent = (marketing_consent_at is not null)),
  constraint leads_status_valid check (status in ('new', 'open', 'waiting', 'resolved', 'spam'))
);
comment on table public.leads is 'Enquiries from the public forms. Insert-only for the public; readable and triaged by staff.';

alter table public.leads enable row level security;
alter table public.leads force row level security;
revoke all on table public.leads from public, anon, authenticated;

create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists leads_status_created_at_idx on public.leads (status, created_at desc);
-- serves the per-address throttle in 0003 and staff search by address
create index if not exists leads_email_created_at_idx on public.leads (email, created_at desc);
create index if not exists leads_assigned_to_idx on public.leads (assigned_to) where assigned_to is not null;

-- ---------------------------------------------------------------------------
-- lead_notes: internal notes by staff. Never visible to the public.
-- `author` is not a foreign key to staff on purpose: a note outlives the
-- removal of the person who wrote it.
-- ---------------------------------------------------------------------------
create table if not exists public.lead_notes (
  id         uuid primary key default gen_random_uuid(),
  lead_id    uuid not null references public.leads (id) on delete cascade,
  author     uuid default auth.uid() references auth.users (id) on delete set null,
  body       text not null,
  created_at timestamptz not null default now(),
  constraint lead_notes_body_valid check (
    char_length(body) between 1 and 4000
    and char_length(btrim(body)) >= 1
    and body !~ '[\u0001-\u0008\u000B-\u001F\u007F]'
  )
);
comment on table public.lead_notes is 'Internal staff notes on a lead.';

alter table public.lead_notes enable row level security;
alter table public.lead_notes force row level security;
revoke all on table public.lead_notes from public, anon, authenticated;

create index if not exists lead_notes_lead_idx on public.lead_notes (lead_id, created_at);

-- ---------------------------------------------------------------------------
-- newsletter_subscribers: one row per address, with consent evidence.
-- ---------------------------------------------------------------------------
create table if not exists public.newsletter_subscribers (
  id              uuid primary key default gen_random_uuid(),
  email           text not null,
  created_at      timestamptz not null default now(),
  source          text not null default 'site',
  consent_at      timestamptz not null,
  consent_version text not null,
  unsubscribed_at timestamptz,
  constraint newsletter_email_valid check (
    char_length(email) between 6 and 254
    and email = lower(email)
    and email ~ '^[a-z0-9.!#$%&''*+/=?^_`{|}~-]+@[a-z0-9-]+(\.[a-z0-9-]+)+$'
  ),
  constraint newsletter_source_valid check (source ~ '^[A-Za-z0-9/_:.-]{1,80}$'),
  constraint newsletter_consent_version_valid check (consent_version ~ '^[A-Za-z0-9._-]{1,40}$')
);
comment on table public.newsletter_subscribers is 'Newsletter subscriptions with consent evidence. Insert-only for the public.';

alter table public.newsletter_subscribers enable row level security;
alter table public.newsletter_subscribers force row level security;
revoke all on table public.newsletter_subscribers from public, anon, authenticated;

-- case-insensitive uniqueness (the CHECK above already forces lower case; the
-- expression index keeps the guarantee even if that constraint is ever relaxed)
create unique index if not exists newsletter_subscribers_email_key on public.newsletter_subscribers (lower(email));
create index if not exists newsletter_subscribers_created_at_idx on public.newsletter_subscribers (created_at desc);

-- ---------------------------------------------------------------------------
-- audit_log: append-only record of staff actions.
-- Written only by SECURITY DEFINER triggers and functions (0002, 0003). No API
-- role has INSERT, UPDATE or DELETE, and 0003 adds triggers that refuse UPDATE,
-- DELETE and TRUNCATE for every role, the table owner included.
-- `actor` is deliberately not a foreign key: the record must survive the
-- deletion of the account it refers to.
-- (An identity column is used instead of bigserial: same bigint sequence, but
-- no separately-grantable sequence object and no way to supply an id by hand.)
-- ---------------------------------------------------------------------------
create table if not exists public.audit_log (
  id        bigint generated always as identity primary key,
  at        timestamptz not null default now(),
  actor     uuid,
  action    text not null,
  entity    text not null,
  entity_id text,
  detail    jsonb not null default '{}'::jsonb,
  constraint audit_log_action_valid check (action ~ '^[a-z_.]{1,60}$'),
  constraint audit_log_entity_valid check (entity ~ '^[a-z_]{1,40}$'),
  constraint audit_log_entity_id_valid check (entity_id is null or char_length(entity_id) <= 80)
);
comment on table public.audit_log is 'Append-only audit trail. Rows are written by triggers; nobody can change or remove them through the API.';

alter table public.audit_log enable row level security;
alter table public.audit_log force row level security;
revoke all on table public.audit_log from public, anon, authenticated;

create index if not exists audit_log_at_idx on public.audit_log (at desc);
create index if not exists audit_log_entity_idx on public.audit_log (entity, entity_id, at desc);
